# Generated by Django 5.1 on 2024-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_logo',
            field=models.ImageField(blank=True, upload_to='students/'),
        ),
    ]
