# Generated by Django 5.1 on 2024-09-15 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('icp', '0002_student_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(help_text="Enter the student's age."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='index',
            field=models.CharField(help_text="Enter the student's index number.", max_length=50),
            preserve_default=False,
        ),
    ]
